env:
  browser: true
  es2021: true
extends:
  - "plugin:react/recommended"
  - google
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
settings:
  version: "latest"
rules: {}
root: true
